//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	config "github.com/gardener/gardener-extension-shoot-traefik/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*TraefikConfig)(nil), (*config.TraefikConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TraefikConfig_To_config_TraefikConfig(a.(*TraefikConfig), b.(*config.TraefikConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TraefikConfig)(nil), (*TraefikConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TraefikConfig_To_v1alpha1_TraefikConfig(a.(*config.TraefikConfig), b.(*TraefikConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TraefikConfigSpec)(nil), (*config.TraefikConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TraefikConfigSpec_To_config_TraefikConfigSpec(a.(*TraefikConfigSpec), b.(*config.TraefikConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TraefikConfigSpec)(nil), (*TraefikConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TraefikConfigSpec_To_v1alpha1_TraefikConfigSpec(a.(*config.TraefikConfigSpec), b.(*TraefikConfigSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_TraefikConfig_To_config_TraefikConfig(in *TraefikConfig, out *config.TraefikConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_TraefikConfigSpec_To_config_TraefikConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TraefikConfig_To_config_TraefikConfig is an autogenerated conversion function.
func Convert_v1alpha1_TraefikConfig_To_config_TraefikConfig(in *TraefikConfig, out *config.TraefikConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_TraefikConfig_To_config_TraefikConfig(in, out, s)
}

func autoConvert_config_TraefikConfig_To_v1alpha1_TraefikConfig(in *config.TraefikConfig, out *TraefikConfig, s conversion.Scope) error {
	if err := Convert_config_TraefikConfigSpec_To_v1alpha1_TraefikConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_TraefikConfig_To_v1alpha1_TraefikConfig is an autogenerated conversion function.
func Convert_config_TraefikConfig_To_v1alpha1_TraefikConfig(in *config.TraefikConfig, out *TraefikConfig, s conversion.Scope) error {
	return autoConvert_config_TraefikConfig_To_v1alpha1_TraefikConfig(in, out, s)
}

func autoConvert_v1alpha1_TraefikConfigSpec_To_config_TraefikConfigSpec(in *TraefikConfigSpec, out *config.TraefikConfigSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.IngressClass = in.IngressClass
	out.IngressProvider = config.IngressProviderType(in.IngressProvider)
	out.LogLevel = in.LogLevel
	return nil
}

// Convert_v1alpha1_TraefikConfigSpec_To_config_TraefikConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_TraefikConfigSpec_To_config_TraefikConfigSpec(in *TraefikConfigSpec, out *config.TraefikConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TraefikConfigSpec_To_config_TraefikConfigSpec(in, out, s)
}

func autoConvert_config_TraefikConfigSpec_To_v1alpha1_TraefikConfigSpec(in *config.TraefikConfigSpec, out *TraefikConfigSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.IngressClass = in.IngressClass
	out.IngressProvider = IngressProviderType(in.IngressProvider)
	out.LogLevel = in.LogLevel
	return nil
}

// Convert_config_TraefikConfigSpec_To_v1alpha1_TraefikConfigSpec is an autogenerated conversion function.
func Convert_config_TraefikConfigSpec_To_v1alpha1_TraefikConfigSpec(in *config.TraefikConfigSpec, out *TraefikConfigSpec, s conversion.Scope) error {
	return autoConvert_config_TraefikConfigSpec_To_v1alpha1_TraefikConfigSpec(in, out, s)
}
